<?php

// Config
//$mandrill_key = 'iDcgCC0GtJZpoTS49edczg';
$mandrill_key = 'aDd3WB7flPIZ1elFRl6-9g'; // Anatolie test key

$sender_email		= 'contact@servercrate.com';
$reciever_email		= 'anatolie@cubemotion.com';

function error( $msg='' ) {
	if ( empty($msg) ) { $msg = 'There was a problem submitting your request. Please try again later.'; }
	header('HTTP/1.0 400 Bad Request');
	echo json_encode(['status' => 'fail', 'msg' => $msg]);
	die();
}

if ( $_SERVER['REQUEST_METHOD'] == 'POST' ) {

	$submit = [
		'name'			=> (empty($_POST['name'])) ? '' : $_POST['name'],
		'email'			=> (empty($_POST['email'])) ? '' : $_POST['email'],
		'phone'			=> (empty($_POST['phone'])) ? '' : $_POST['phone'],
		'quantity'	=> (empty($_POST['quantity'])) ? '' : $_POST['quantity'],
		'message'		=> (empty($_POST['message'])) ? '' : $_POST['message']
	];

	// Name checks
	if ( empty($submit['name']) ) {
		error('Please enter your full name.');
	}
	if ( strlen($submit['name']) > 50 ) {
		error('Full name cannot be longer than 50 characters.');
	}

	// Email checks
	if ( empty($submit['email']) ) {
		error('Please enter your email address.');
	}
	if ( strlen($submit['email']) > 100 ) {
		error('Email address cannot be longer than 100 characters.');
	}
	if ( filter_var($submit['email'], FILTER_VALIDATE_EMAIL) == false ) {
		error('Please enter a valid email address.');
	}

	// Phone checks
	if ( strlen($submit['phone']) > 30 ) {
		error('Phone number cannot be longer than 30 characters.');
	}

	// Quantity checks
	if ( empty($submit['quantity']) ) {
		error('Please select a quantity.');
	}

	$valid_quantities = ['50', '150', '250', 'custom'];
	if ( !in_array($submit['quantity'], $valid_quantities) ) {
		error('Phone select a valid quantity.');
	}

	// Message checks
	if ( empty($submit['message']) ) {
		error('Please enter a message.');
	}
	if ( strlen($submit['message']) < 50 ) {
		error('Message must be at least 50 characters.');
	}
	if ( strlen($submit['message']) > 1500 ) {
		error('Message cannot be longer than 1500 characters.');
	}
	
	require_once 'src/Mandrill.php';

	try {

		$mandrill = new Mandrill($mandrill_key);

		$html = '
		<!DOCTYPE html>
		<html style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
		<head>
		<meta name="viewport" content="width=device-width">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Contact Request</title>
		</head>
		<body bgcolor="#f6f6f6" style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; -webkit-font-smoothing: antialiased; height: 100%; -webkit-text-size-adjust: none; width: 100% !important; margin: 0; padding: 0;">
		<table class="body-wrap" bgcolor="#f6f6f6" style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; width: 100%; margin: 0; padding: 20px;"><tr style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
		<td style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;"></td>
		<td class="container" bgcolor="#FFFFFF" style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; clear: both !important; display: block !important; max-width: 800px !important; Margin: 0 auto; padding: 20px; border: 1px solid #f0f0f0;">
			<div class="content" style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; display: block; max-width: 800px; margin: 0 auto; padding: 0;">
			<table style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; width: 100%; margin: 0; padding: 0;"><tr style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
			<td style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;">
			<h1 style="font-family: \'Helvetica Neue\', Helvetica, Arial, \'Lucida Grande\', sans-serif; font-size: 36px; line-height: 1.2em; color: #111111; font-weight: 200; margin: 0 0 15px 0; padding: 0;">Contact Request</h1>
			<p style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6em; font-weight: normal; margin: 0 0 20px 0; padding: 0;">This is an automatic email generated by the contact form on the website.</p>
			<p style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6em; font-weight: normal; margin: 0 0 10px; padding: 0;"><b>Full Name</b><br>'.$submit['name'].'</p>
			<p style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6em; font-weight: normal; margin: 0 0 10px; padding: 0;"><b>Email</b><br>'.$submit['email'].'</p>
			<p style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6em; font-weight: normal; margin: 0 0 10px; padding: 0;"><b>Phone</b><br>'.$submit['phone'].'</p>
			<p style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6em; font-weight: normal; margin: 0 0 10px; padding: 0;"><b>Proxy Quantity</b><br>'.$submit['quantity'].'</p>
			<p style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6em; font-weight: normal; margin: 0 0 10px; padding: 0;"><b>Message</b><br>'.nl2br($submit['message']).'</p>
			<p style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6em; font-weight: normal; margin: 30px 0 0 0; padding: 0;">Submitted from <b>'.$_SERVER['REMOTE_ADDR'].'</b></p>
			</td>
			</tr></table>
		</div>
		</td>
		<td style="font-family: \'Helvetica Neue\', \'Helvetica\', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6em; margin: 0; padding: 0;"></td>
		</tr></table>
		</body>
		</html>';

		$message = [
			'html'			=> $html,
			'subject'		=> 'Contact Form Request (from '+$submit['name']+')',
			'from_email'	=> $sender_email,
			'from_name'		=> 'Contact Form',
			'to'			=> [
				['email' => $reciever_email, 'type' => 'to']
			],
			'headers'		=> ['Reply-To' => $submit['email']],
			'important'		=> true,
		];

		$result = $mandrill->messages->send($message);

		echo json_encode(['status' => 'success']);
		die();

	} catch(Mandrill_Error $e) {
		error();
	}

} else {
	header('HTTP/1.0 403 Forbidden');
}